version: '3'

services:
  mysql:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - 'kotlin-bootcamp-data:/var/lib/mysql'
  memcached:
    image: memcached
    ports:
      - '11211:11211'
volumes:
  kotlin-bootcamp-data:
